### ISSUE TITLE
"restart: always" In docker-compose.yaml File Not Starting Containers

### ISSUE THREAD

**Issue by BipedalPrimate** [victronenergy/venus-grafana#11]
Have added the "restart: always" option to each of the containers in the docker-compose.yaml file as per https://github.com/victronenergy/venus-grafana#33-automatic-restart, yet when docker desktop is started, the containers do not start.

The "restart: always" was added AFTER Victron Grafana was installed.

Is the yaml file only considered when Victron Grafana is installed?

If so, is there a way to implement the "restart: always" option after the install?

**Comment by mman** [comment]
What platform is that on please? Docker desktop for Mac or Windows? Could you please post full docker-compose.yaml for a reference. What happens when you docker compose up a file, docker will create containers and sets their properties according to the compose file. Then the file is not used anymore (that is until you invoke some other docker compose command and specify the file as a reference) and after reboot the information is taken from docker itself.

I am sure that docker restart works on Linux, and should work on Mac where I have seen it restart containers automatically after I quit/update docker desktop itself.

**Comment by BipedalPrimate** [comment]
Am using Docker Desktop on Windows 10.

docker-compose.yaml

```
version: '3.4'
services:
  server:
    image: "victronenergy/venus-docker-server:latest"
    ports:
     - "8088:8088"
    volumes:
     - "config-storage:/config"
    restart: always
  upnp:
    image: "victronenergy/venus-docker-upnp:latest"
    network_mode: host
    restart: always
  influxdb:
    image: "influxdb:1.7"
    ports:
     - "8086:8086"
    volumes:
     - "influxdb-storage:/var/lib/influxdb"
    environment:
     - INFLUXDB_HTTP_LOG_ENABLED=false
    restart: always
  graphing:
    image: "victronenergy/venus-docker-grafana:latest"
    volumes:
     - "grafana-storage:/var/lib/grafana"
    ports:
     - "3000:3000"
    restart: always
    
volumes:
 influxdb-storage:
 grafana-storage:
 config-storage:
```

Note that I have also tried using a single `restart: always` line at the end of the docker-compose.yaml file.

The symptoms correspond to your description of how docker-compose.yaml is used - not referenced on restart of Docker Desktop.

As I reluctant to reinstall as I am worried I might lose all custom Dashboards and history, is there a way to implement the `restart: always` option after the install?
