### ISSUE TITLE
404 page not found InfluxDB Webserver

### ISSUE THREAD

**Issue by BLVCKRIPPER1337** [victronenergy/venus-grafana#40]
Hey, after the commit in Docker compose everything has downloaded and installed in Docker correctly, Grafana gets the data from the cerbo everything good. Via http I get: 404 page not found and via https i get: Error: SSL_ERROR_RX_RECORD_TOO_LONG
thanks

**Comment by mman** [comment]
More details please, the `docker-compose.yaml` does not mention TLS/SSL anywhere, and none of the code in Influx Loader or Grafana itself touches TLS/SSL at all. 

So my assumption is that this is your own setup somewhere. Could you post your `docker-compose.yaml` and exact URL that you are accessing and that is failing?

The last commits only bumped the docker image version, and do not change anything special in how is everything setup.

**Comment by BLVCKRIPPER1337** [comment]
This is a clean install without anything old stuff.



HTTP Error:

My internal IP: https://192.168.111.80:8086/ 


```
Fehler: Gesicherte Verbindung fehlgeschlagen

Beim Verbinden mit 192.168.111.80:8086 trat ein Fehler auf. SSL hat einen Eintrag erhalten, der die maximal erlaubte Länge überschritten hat.

Fehlercode: SSL_ERROR_RX_RECORD_TOO_LONG

    Die Website kann nicht angezeigt werden, da die Authentizität der erhaltenen Daten nicht verifiziert werden konnte.
    Kontaktieren Sie bitte den Inhaber der Website, um ihn über dieses Problem zu informieren.
```

```
version: '3.4'
services:
  loader:
    image: "victronenergy/venus-influx-loader:1.6"
    command: [ "bin/venus-influx-loader", "--enable-discovery-api" ]
    ports:
     - "8088:8088"
    volumes:
     - "config-storage:/config"
  browser:
    image: "victronenergy/venus-influx-loader:1.6"
    command: [ "bin/venus-upnp-browser", "--discovery-api", "http://localhost:8088/discovery-api/" ]
    # `network_mode: host` is required for the `venus-upnp-browser` to access your host network
    # and audo discover Venus devices.
    network_mode: host
  influxdb:
    image: "influxdb:1.8"
    ports:
     - "8086:8086"
    volumes:
     - "influxdb-storage:/var/lib/influxdb"
    environment:
     - INFLUXDB_HTTP_LOG_ENABLED=false
  grafana:
    image: "victronenergy/venus-grafana:1.6"
    volumes:
     - "grafana-storage:/var/lib/grafana"
    ports:
     - "3000:3000"
    environment:
     - VIL_INFLUXDB_URL=http://influxdb:8086
     - VIL_GRAFANA_API_URL=http://loader:8088/grafana-api
     # specify URL that should be listed on Welcome dashboard
     # to acess Venus Influx Loader Admin UI
     - VIL_PUBLIC_URL=http://localhost:8088/

volumes:
  influxdb-storage:
  grafana-storage:
  config-storage:

```
